[project]
name = "promptflow-example"
version = "0.1.0"
requires-python = ">=3.11, <3.12"
dependencies = [
    "maincontentextractor>=0.0.4",
    "promptflow",
    "promptflow-tools @ git+https://github.com/microsoft/promptflow.git@promptflow_1.17.1#subdirectory=src/promptflow-tools",
]
